---
    - name: Installing Apache2 webserver
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ package_name }}"

    - name: Copying virtual host configuration
      ansible.builtin.template:
        src: apache.conf.j2
        dest: "{{ http_config }}"
        mode: 0644
      notify: Restarted Apache2

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Restarted Apache2